config {
  type: "operations",
  tags: ["daily"]
}

-- Use dataform.projectConfig.vars.run_date if you need it in the DECLARE
DECLARE run_date DATE DEFAULT DATE("${dataform.projectConfig.vars.run_date}");

-- Using the variable in the table name
CREATE OR REPLACE TABLE `${dataform.projectConfig.defaultDataset}.clean_events_${dataform.projectConfig.vars.run_date}` AS
SELECT
  user_id,
  event_time
FROM `${dataform.projectConfig.defaultDataset}.raw_events`
WHERE DATE(event_time) = run_date;